### PR TITLE
Fix a NameError in plist

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by guidovranken** [comment]
I think you meant to catch `plistlib.InvalidFileException` ?

**Comment by guidovranken** [comment]
It also throws this:

```
Traceback (most recent call last):
  File "<string>", line 5, in FuzzerRunOne
  File "/home/jhg/python-fuzzers/oss-fuzz/build/out/python3-libraries/cpython-install/lib/python3.12/plistlib.py", line 892, in loads
    return load(fp, fmt=fmt, dict_type=dict_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhg/python-fuzzers/oss-fuzz/build/out/python3-libraries/cpython-install/lib/python3.12/plistlib.py", line 884, in load
    return p.parse(fp)
           ^^^^^^^^^^^
  File "/home/jhg/python-fuzzers/oss-fuzz/build/out/python3-libraries/cpython-install/lib/python3.12/plistlib.py", line 186, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: unclosed token: line 1, column 0
```

Since this is using XML, are you sure this won't cause random local files to be read? How about the other fuzzers you submitted?

A fuzzer doing random file (or network) IO is not preferred.

**Comment by jvoisin** [comment]
It shouldn't, no. But Python has this horrible tendency to raise undocumented exceptions :/

**Comment by jvoisin** [comment]
> I think you meant to catch plistlib.InvalidFileException ?

Indeed.

**Pull request closed without merging**
